### PR TITLE
Fix issue #55

### LINKED ISSUE #55: Analysis misses some dependencies
This problem was discovered in conversation for PR https://github.com/checkstyle/checkstyle/pull/7960, which is about optimizing the methods distance in `checkstyle.api.FileText` class.

A quick look at that class shows us that `public int size()` is used in `findLineBreaks()`,
but for some reason analysis does not capture that dependency.

To visualize this yourself, checkout the provided [dsm report](https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/after.FileText.java.html).

### PR DESCRIPTION
**Pull request by wilcoln**
Resolve #55 
- Report before fix: https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/after.FileText.java.html
- Report after fix: https://wilcoln.github.io/com.pupppycrawl.tools.checkstyle.api/after.fix.FileText.java.html

I would like to mention that the `isAnonymousClassDef` method is already defined in `RequireThisCheck` (Cf checkstyle main repo), as you might recall, I'm working on refactoring this check in order to extract some common logic to utility classes like `TokenUtil` and a new `FrameUtil`. 
As for the method  `isAnonymousClassDef`, I'm planning to place it inside `TokenUtil`.

Once it's done, line 47 of `AnalysisUtils.java` will become
 ```java
result = !TokenUtil.isAnonymousClassDef(parent);
 ```

### CODE REVIEW

File: methods-distance/src/main/java/com/github/sevntu/checkstyle/analysis/AnalysisUtils.java [hunk 1]
```diff
@@ -116,4 +118,16 @@ public static DetailAST getClosestParentOfTypes(DetailAST node, Integer... ofTyp
...
+
+    /**
+     * Whether the AST is a definition of an anonymous class.
+     *
+     * @param ast the AST to process.
+     * @return true if the AST is a definition of an anonymous class.
+     */
+    private static boolean isAnonymousClassDef(DetailAST ast) {
+        final DetailAST lastChild = ast.getLastChild();
+        return lastChild != null
```
Comment (rnveach) [inline methods-distance/src/main/java/com/github/sevntu/checkstyle/analysis/AnalysisUtils.java:130]: Can last child ever be `null`?
````
t= new Test();
t= new Test() {};

   |      |--EXPR -> EXPR [3:1]
    |      |  `--ASSIGN -> = [3:1]
    |      |      |--IDENT -> t [3:0]
    |      |      `--LITERAL_NEW -> new [3:3]
    |      |          |--IDENT -> Test [3:7]
    |      |          |--LPAREN -> ( [3:11]
    |      |          |--ELIST -> ELIST [3:12]
    |      |          `--RPAREN -> ) [3:12]
    |      |--SEMI -> ; [3:13]
    |      |--EXPR -> EXPR [4:1]
    |      |  `--ASSIGN -> = [4:1]
    |      |      |--IDENT -> t [4:0]
    |      |      `--LITERAL_NEW -> new [4:3]
    |      |          |--IDENT -> Test [4:7]
    |      |          |--LPAREN -> ( [4:11]
    |      |          |--ELIST -> ELIST [4:12]
    |      |          |--RPAREN -> ) [4:12]
    |      |          `--OBJBLOCK -> OBJBLOCK [4:14]
    |      |              |--LCURLY -> { [4:14]
    |      |              `--RCURLY -> } [4:15]
````

Comment (wilcoln) [reply methods-distance/src/main/java/com/github/sevntu/checkstyle/analysis/AnalysisUtils.java:130]: Seems like it can't. I'll rewrite the `isAnonymousClassDef` method in checkstyle main repo accordingly, then I'll come back here and apply the change mentioned in my first comment.
Thank you.

Comment (rnveach) [reply methods-distance/src/main/java/com/github/sevntu/checkstyle/analysis/AnalysisUtils.java:130]: Main repo is alot more strict than this repo. It uses pitest and such. I would expect it to have a reason for this code. Maybe its for Java 8 code like `::new` or similar.

Comment (wilcoln) [reply methods-distance/src/main/java/com/github/sevntu/checkstyle/analysis/AnalysisUtils.java:130]: @rnveach, after some investigation, seems like last child can, indeed, be null.

`cat Test.java` 
```java
public class InputRequireThisMethodReferences {

    {
        Arrays.stream(new String[] {}).collect(Collectors.toCollection(TreeSet::new));
    }
}
```
`java -jar checkstyle-8.31-all.jar -t Test.java`
```
CLASS_DEF -> CLASS_DEF [1:0]
|--MODIFIERS -> MODIFIERS [1:0]
|   `--LITERAL_PUBLIC -> public [1:0]
|--LITERAL_CLASS -> class [1:7]
|--IDENT -> InputRequireThisMethodReferences [1:13]
`--OBJBLOCK -> OBJBLOCK [1:46]
    |--LCURLY -> { [1:46]
    |--INSTANCE_INIT -> INSTANCE_INIT [3:4]
    |   `--SLIST -> { [3:4]
    |       |--EXPR -> EXPR [4:46]
    |       |   `--METHOD_CALL -> ( [4:46]
    |       |       |--DOT -> . [4:38]
    |       |       |   |--METHOD_CALL -> ( [4:21]
    |       |       |   |   |--DOT -> . [4:14]
    |       |       |   |   |   |--IDENT -> Arrays [4:8]
    |       |       |   |   |   `--IDENT -> stream [4:15]
    |       |       |   |   |--ELIST -> ELIST [4:22]
    |       |       |   |   |   `--EXPR -> EXPR [4:22]
    |       |       |   |   |       `--LITERAL_NEW -> new [4:22]
    |       |       |   |   |           |--IDENT -> String [4:26]
    |       |       |   |   |           |--ARRAY_DECLARATOR -> [ [4:32]
    |       |       |   |   |           |   `--RBRACK -> ] [4:33]
    |       |       |   |   |           `--ARRAY_INIT -> { [4:35]
    |       |       |   |   |               `--RCURLY -> } [4:36]
    |       |       |   |   `--RPAREN -> ) [4:37]
    |       |       |   `--IDENT -> collect [4:39]
    |       |       |--ELIST -> ELIST [4:70]
    |       |       |   `--EXPR -> EXPR [4:70]
    |       |       |       `--METHOD_CALL -> ( [4:70]
    |       |       |           |--DOT -> . [4:57]
    |       |       |           |   |--IDENT -> Collectors [4:47]
    |       |       |           |   `--IDENT -> toCollection [4:58]
    |       |       |           |--ELIST -> ELIST [4:78]
    |       |       |           |   `--EXPR -> EXPR [4:78]
    |       |       |           |       `--METHOD_REF -> :: [4:78]
    |       |       |           |           |--IDENT -> TreeSet [4:71]
    |       |       |           |           `--LITERAL_NEW -> new [4:80]
    |       |       |           `--RPAREN -> ) [4:83]
    |       |       `--RPAREN -> ) [4:84]
    |       |--SEMI -> ; [4:85]
    |       `--RCURLY -> } [5:4]
    `--RCURLY -> } [6:0]
```
